### ISSUE TITLE
TypeError: this.Connection is not a constructor

### ISSUE THREAD

**Issue by jimmone** [compwright/aws-elasticsearch-connector#1]
I'm getting the following error when trying to create a client:

`.../node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:57
    const connection = new this.Connection(opts)
                       ^
TypeError: this.Connection is not a constructor`

**Comment by furudean** [comment]
Show us some code please, an error trace is not very helpful.

**Comment by jimmone** [comment]
Here is the code where I'm trying to initialize the client:

```
import * as AWS from 'aws-sdk';
import { Client } from '@elastic/elasticsearch'
import AmazonConnection from 'aws-elasticsearch-connector'
import { ES_DOMAIN } from '../constants/index'

if (process.env.NODE_ENV === 'development') {
  AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: 'my-profile' });
}

export const esClient = new Client({
  node: ES_DOMAIN,
  Connection: AmazonConnection
});
```

**Comment by jimmone** [comment]
Seems like it has something to do with tsconfig. After I ran the command tsc --init it started working.
