### ISSUE TITLE
AWS ElasticSearch Custom domain names not connecting

### ISSUE THREAD

**Issue by vyeturu** [compwright/aws-elasticsearch-connector#24]
Below issue occurring when connecting to AWS ElasticSearch custom endpoint. It is fine with vpc endpoint.
2020-11-18T07:20:34.250Z	d2ad8d95-5a42-533e-abfb-d5bb97322dfd	INFO	ResponseError: Response Error
    at onBody (/var/task/node_modules/@elastic/elasticsearch/lib/Transport.js:311:23)
    at IncomingMessage.onEnd (/var/task/node_modules/@elastic/elasticsearch/lib/Transport.js:240:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by vyeturu** [comment]
I used below specific code model.
const { Client } = require('@elastic/elasticsearch')
const AWS = require('aws-sdk')
const createAwsElasticsearchConnector = require('aws-elasticsearch-connector')

const awsConfig = new AWS.Config({
  // Set the accesskey, secretAccessKey, region})

const client = new Client({
  ...createAwsElasticsearchConnector(awsConfig),
  node: 'https://my-elasticsearch-cluster.us-east-1.es.amazonaws.com' // here the url is custom end point ..not vpc
})

**Comment by chsing** [comment]
I am having the same issue when using a custom domain name for my ES cluster endpoint. This is the error message I'm getting from the ES client:

` body: {
      message: "Credential should be scoped to a valid region, not 'us-east-1'. "
    },`

I believe this is because the connector is not honoring the region being set in the AWS.config object. Here is the code I am using:

```// Packages
const { Client } = require('@elastic/elasticsearch');
const AWS = require('aws-sdk');
const createAwsElasticsearchConnector = require('aws-elasticsearch-connector');

const createElasticsearchClient = elasticsearchEndpoint => {
  AWS.config.update({ region: 'us-west-2' });
  return new Client({
    ...createAwsElasticsearchConnector(AWS.config),
    node: elasticsearchEndpoint,
  });
};
```

However, the error message above implies the connection is using the 'us-east-1' region instead, which is the default region if one is not provided.
