### ISSUE TITLE
Broken with @elastic/elasticsearch@7.14.0

### ISSUE THREAD

**Issue by oguimbal** [compwright/aws-elasticsearch-connector#29]
Hi ! 

[FYI](https://github.com/elastic/elasticsearch-js/issues/1521)

**Comment by gustavolsilvano** [comment]
Hello! @oguimbal 
I tried to use @elastic/elasticsearch 7.13, but it still return me this issue. Do you have a workaround for this?
![image](https://user-images.githubusercontent.com/58196647/130654480-b24a0085-fa82-4018-be4d-279243b8d6b8.png)

**Comment by oguimbal** [comment]
Really ?
I just double-checked, its working for us in production with `@elastic/elasticsearch@7.13` (and `aws-elasticsearch-connector@9.0.3`) 😕

**Comment by carlnordenfelt** [comment]
> Hello! @oguimbal
> I tried to use @elastic/elasticsearch 7.13, but it still return me this issue. Do you have a workaround for this?
> ![image](https://user-images.githubusercontent.com/58196647/130654480-b24a0085-fa82-4018-be4d-279243b8d6b8.png)

Check you lock file. You have targeted ^7.13.0. which may install a later minor version, e.g. 7.14.0 which is the one seemingly introducing the problem. Change your dependency to `"7.13.0"` to ensure that you are running the expected version.

**Comment by harissarwar** [comment]
I tried different 7.x versions. It works with @elastic/elasticsearch@7.6.0. I get the above error with 7.7.0 and newer ones. 
I am using 
- node v16.8.0
- npm v7.21.0

**Comment by luisfavila** [comment]
@compwright doesn't seem to be fixed.
I'm guetting the same error using `@elastic/elasticsearch@7.10.0` and `aws-elasticsearch-connector@9.2.0` on a `.search()`:

```
TypeError: Cannot read properties of null (reading 'then')
    at Object.then (/project/node_modules/@elastic/elasticsearch/lib/Transport.js:151:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by compwright** [comment]
@luisfavila please provide a complete example that reproduces the issue. If you can provide that, I'll reopen this issue and work on a fix.
