### ISSUE TITLE
Example code at top of readme doesn't work

### ISSUE THREAD

**Issue by greim** [compwright/aws-elasticsearch-connector#7]
The `awsConfig` object isn't being passed to the `AmazonConnection` constructor by `es.Client`.
```js
const client = new Client({
  node: 'my-elasticsearch-cluster.us-east-1.es.amazonaws.com',
  Connection: AmazonConnection,
  awsConfig: { credentials: { ... } } // <-- doesn't work
});
```
I determined this by inspecting the [options object here](https://github.com/compwright/aws-elasticsearch-connector/blob/ced1912dab8f9c0b4229bc07c77023a302056a27/src/AmazonConnection.js#L7) which didn't have an `awsConfig` property, and also looking at where the [options are passed](https://github.com/elastic/elasticsearch-js/blob/b439b6cb5a4515a890cd25fa58606629fcf49ef7/lib/pool/BaseConnectionPool.js#L57). This lib [falls back](https://github.com/compwright/aws-elasticsearch-connector/blob/ced1912dab8f9c0b4229bc07c77023a302056a27/src/AmazonConnection.js#L9) to whatever `AWS.config` is at the moment, which is fine, but in my case happened to be the wrong value.

I'm using @elastic/elasticsearch@7.4.0.

**Comment by jp-simons** [comment]
Yeah, I tried using this the way the example code does and `awsConfig: { credentials }` seems to be ignored. I can keep using the old ES client for now, but would be cool to upgrade soon.

**Comment by aleksieiev** [comment]
@greim @johnnysprinkles 
Actually it works, but in a little bit tricky way that expected. Problem is that `AmazonConnection` class receives `options` parameter which has been provided during Connection creation. Let's try to find who provides these options.

1. Elasticsearch library starts to initialize connection/connection pool (see [here](https://github.com/elastic/elasticsearch-js/blob/master/index.js#L106))
2. In case of nothing specific [BaseConnectionPool](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js) will be created.
3. `BaseConnectionPool` uses already existing connections and provided `opts` for connections initialization ( see [here](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L90) ). Suppose it's the first connection, so the array will contain only `opts` parameter.
4. And the very interesting method is [createConnection](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L40): it receives `opts` which is only `node` section from Client configuration and uses only it. All in all, [here](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L57) a new instance of `AmazonConnection` will be created and how can you see only `opts` section is provided. As a result, all attributes of 'node' or 'nodes' will be available in `AmazonConnection` class.

So, the final working configuration is the next: 

```
const {URL} = require('url');
const {AmazonConnection} = require('aws-elasticsearch-connector');
const {Client} = require('@elastic/elasticsearch');

const client = new Client({
  node: {
    url: new URL('https://my-elasticsearch-cluster.us-east-1.es.amazonaws.com'),
    awsConfig: { 
      credentials: {
        accessKeyId: 'your_key',
        secretAccessKey: 'your_secret',
        sessionToken: 'your_token'
      }
    }
  }
  Connection: AmazonConnection,  
});
```

Looks like the author doesn't look at PRs, so it's useless to send a PR with documentation changes. Hope all interested in the solution will find this answer and save their time.

**Comment by devagirir** [comment]
I have an aws elasticsearch where policies were defined as
`{
  "Version": "***-**-**",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::**********:user/****@****.com"
      },
      "Action": [
        "es:ESHttpGet",
        "es:ESHttpDelete",
        "es:ESHttpHead",
        "es:ESHttpPost",
        "es:ESHttpPut"
      ],
      "Resource": "arn:aws:es:us-east-1:********:domain/*******/*"
    }
  ]
}`
If you specify an account, user, or role in this policy, you must sign your requests.
AWS documentation says If you specify an account, user, or role in this policy, you must sign your requests. 

Can you help me how to sign requests with aws-elasticsearch-connector module. Following is my current code which works if we dont specify policies.
`
const {Client} = require('@elastic/elasticsearch');

AWS.config.update({
    credentials: new AWS.Credentials(accessKey, secretAccessKey),
    region
  });
const client = new Client(
  {
    node: url,
    connectionClass: AmazonConnection,
    requestTimeout: getElasticClientTimeout()
  });
`

**Comment by devagirir** [comment]
> @greim @johnnysprinkles
> Actually it works, but in a little bit tricky way that expected. Problem is that `AmazonConnection` class receives `options` parameter which has been provided during Connection creation. Let's try to find who provides these options.
> 
> 1. Elasticsearch library starts to initialize connection/connection pool (see [here](https://github.com/elastic/elasticsearch-js/blob/master/index.js#L106))
> 2. In case of nothing specific [BaseConnectionPool](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js) will be created.
> 3. `BaseConnectionPool` uses already existing connections and provided `opts` for connections initialization ( see [here](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L90) ). Suppose it's the first connection, so the array will contain only `opts` parameter.
> 4. And the very interesting method is [createConnection](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L40): it receives `opts` which is only `node` section from Client configuration and uses only it. All in all, [here](https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L57) a new instance of `AmazonConnection` will be created and how can you see only `opts` section is provided. As a result, all attributes of 'node' or 'nodes' will be available in `AmazonConnection` class.
> 
> So, the final working configuration is the next:
> 
> ```
> const {URL} = require('url');
> const {AmazonConnection} = require('aws-elasticsearch-connector');
> const {Client} = require('@elastic/elasticsearch');
> 
> const client = new Client({
>   node: {
>     url: new URL('https://my-elasticsearch-cluster.us-east-1.es.amazonaws.com'),
>     awsConfig: { 
>       credentials: {
>         accessKeyId: 'your_key',
>         secretAccessKey: 'your_secret',
>         sessionToken: 'your_token'
>       }
>     }
>   }
>   Connection: AmazonConnection,  
> });
> ```
> 
> Looks like the author doesn't look at PRs, so it's useless to send a PR with documentation changes. Hope all interested in the solution will find this answer and save their time.

How to sign requests with aws-elasticsearch-connector module

**Comment by compwright** [comment]
Did you try the third option listed in the README?

> ### With asynchronous or refreshing credentials from AWS
> 
> When reading AWS credentials from an IAM role or an EC2/ECS profile, the credentials
> will be retrieved and refreshed automatically. In this case you'll need to use the
> bundled `AmazonTransport` transport which will call AWS.Config.getCredentials()
> before each ElasticSearch request to ensure that the latest credentials are used.
> 
> ```javascript
> const { Client } = require('@elastic/elasticsearch');
> const { AmazonConnection, AmazonTransport } = require('aws-elasticsearch-connector');
> 
> const client = new Client({
>   node: 'my-elasticsearch-cluster.us-east-1.es.amazonaws.com',
>   Connection: AmazonConnection,
>   Transport: AmazonTransport
> });
> ```

**Comment by compwright** [comment]
@aleksieiev for the record, I would be happy to entertain any PR that fixes an issue or improves this library or its documentation, including the README.

@greim please give the AmazonTransport a try, as illustrated above. If that doesn't fix the issue, we can reopen this and discuss further.
