### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by Veetaha** [compwright/aws-elasticsearch-connector#8]
Could you please provide a simple index.d.ts file to enable the usage of this package in TypeScript codebase?

**Comment by compwright** [comment]
I don't use Typescript for this library, and personally have no experience with it. I'd happily entertain a PR if you'd like to try your hand at setting it up!

**Comment by schimini** [comment]
I've forked the project to provide the typings and i ended up just replicating the code in typescript. You can clone it and run build and it generates the types files (and ofc js files) and you can add them to the project if you feel like it. 
I'm not be any means good at defining types but i just did it so you could have a look at it.

**Comment by danrivett** [comment]
I'd also love to see TS types for this project. I know @compwright has no experience with TS, but given @schimini's [fork](https://github.com/schimini/aws-elasticsearch-connector) I was wondering if you would entertain merging a PR from his fork into this repository and publishing a new version to npm?

I can add a dependency on @schimini's fork, but would prefer to depend on a package in npm if possible.

**Comment by danrivett** [comment]
A quick follow up, but I have a workaround in the meantime which I'm not sure if it is a) correct or b) helpful, but I've included it below in case both are true.

I simply created a local types file under `@types/aws-elasticsearch-connector.d.ts` with the following contents:

```ts
declare module 'aws-elasticsearch-connector' {
  import { Connection, Transport } from '@elastic/elasticsearch';
  import AWS from 'aws-sdk';

  export type Connector = {
    Connection: typeof Connection;
    Transport: typeof Transport;
  };

  export const ConnectorFactory: (awsConfig: AWS.Config) => Connector;

  export default ConnectorFactory;
}
```

Seemed simple enough given the size of this package, but not sure if I'm missing anything.

**Comment by logemann** [comment]
would love to see a new release with @danrivett change. Should be ok enough and better than nothing :-)

Dan, could you make PR for this? Perhaps the author will merge it ....

**Comment by jagadeesh93** [comment]
@compwright Hii Sir , Is the typescript declaration file merged with the repo? , @danrivett

**Comment by compwright** [comment]
@jagadeesh93 @danrivett @schimini no pull request has been submitted. Would appreciate help with this issue.

**Comment by schimini** [comment]
I can do it today, in a few hours. Is it ok?

**Comment by compwright** [comment]
Sure, thanks @schimini

**Comment by danrivett** [comment]
Thanks @schimini I appreciate it too.

I completely forgot to follow up on this as my workaround above has been sufficient, but fixing in this repo is much better.

**Comment by jagadeesh93** [comment]
@compwright @danrivett @schimini Thank you everyone for you kind support , The definition provided by @danrivett works fine for me , since my project is deployed on a server and during the build it is taking from npm, there its failing , It would be very helpful if @compwright can merge the type definition from @danrivett or @schimini

**Comment by schimini** [comment]
@danrivett ended up using your typings cause the generated ones were awkward to read. 

@compwright #30  ( I don't know how github notifications work )

**Comment by schimini** [comment]
Bump @compwright ! ( I wanted to delete my fork plz )
